import Link from "next/link";
import { ArrowLeft, LockKeyhole } from "lucide-react";
import { buttonBaseClassName, Surface } from "@/components/admin/primitives";
import { publicEnv } from "@/lib/config/env";
import { PLATFORM_NAME, PLATFORM_OWNER } from "@/lib/constants/platform";
import { cx } from "@/lib/utils/cx";
import { login } from "./actions";

type LoginPageProps = {
  searchParams?: Promise<{
    error?: string;
    next?: string;
  }>;
};

export default async function LoginPage({ searchParams }: LoginPageProps) {
  const resolvedSearchParams = searchParams ? await searchParams : undefined;
  const errorMessage = resolvedSearchParams?.error;
  const nextPath = resolvedSearchParams?.next ?? "/admin";
  const isClientAdmin = publicEnv.deploymentMode === "admin";
  const clientName = publicEnv.clientName;
  const loginContent = isClientAdmin
    ? {
        eyebrow: `${clientName} Admin`,
        heroTitle: `Manage ${clientName} orders, menu, branches, and delivery from one place.`,
        heroDescription:
          "Track incoming orders, keep your catalog updated, manage branch availability, and route customer orders smoothly through WhatsApp.",
        featureCards: [
          "Live order dashboard",
          "Menu & product control",
          "Branch delivery settings",
          "WhatsApp order routing",
        ],
        accessLabel: "Manager access",
        formTitle: `Sign in to ${clientName} Admin`,
        formDescription: `Use your authorized ${clientName} admin account to manage orders and restaurant operations.`,
        helperText:
          "Access is restricted to approved owners and managers. Contact Naptime AI if you need login support.",
        emailPlaceholder:
          clientName.toLowerCase() === "smogy ice"
            ? "owner@smogyice.com"
            : "owner@restaurant.com",
        ctaLabel: "Sign in to dashboard",
        backHref: publicEnv.clientWebsiteUrl || "/",
        backLabel: `Back to ${clientName} website`,
      }
    : {
        eyebrow: PLATFORM_OWNER,
        heroTitle: "NapCart admin for WhatsApp-first restaurant operations.",
        heroDescription:
          "Configure restaurant identity, branches, operating rules, and WhatsApp routing while staff continues receiving orders in WhatsApp.",
        featureCards: [
          "Owner-facing dashboard",
          "Branch availability controls",
          "Restaurant identity settings",
          "WhatsApp route management",
        ],
        accessLabel: "Admin access",
        formTitle: "Sign in to the control layer",
        formDescription:
          "Use the restaurant admin account created during setup.",
        helperText:
          "Demo credentials are generated by the seed script and stored in the local setup notes.",
        emailPlaceholder: "owner@restaurant.com",
        ctaLabel: "Sign in",
        backHref: "/",
        backLabel: `Back to ${PLATFORM_NAME} overview`,
      };

  return (
    <main
      className={cx(
        "min-h-screen px-4 py-6 text-foreground lg:px-6",
        isClientAdmin
          ? "bg-[radial-gradient(circle_at_12%_10%,rgba(100,43,147,0.08),transparent_34%),linear-gradient(180deg,#fff_0%,#fbf7fc_100%)]"
          : "bg-background",
      )}
    >
      <div className="mx-auto grid min-h-[calc(100vh-3rem)] max-w-6xl gap-4 lg:grid-cols-[1fr_440px]">
        <Surface
          className={cx(
            "flex flex-col justify-between overflow-hidden p-8 text-primary-foreground lg:p-10",
            isClientAdmin
              ? "relative border-[#6f3a9a]/20 bg-[radial-gradient(circle_at_16%_12%,rgba(255,138,61,0.18),transparent_28%),radial-gradient(circle_at_86%_90%,rgba(255,255,255,0.16),transparent_30%),linear-gradient(135deg,#642B93_0%,#522178_48%,#34104f_100%)] shadow-[0_24px_80px_rgba(100,43,147,0.22)]"
              : "bg-primary",
          )}
        >
          {isClientAdmin ? (
            <>
              <div className="pointer-events-none absolute -right-24 -top-24 h-64 w-64 rounded-full bg-white/10 blur-3xl" />
              <div className="pointer-events-none absolute -bottom-28 left-16 h-64 w-64 rounded-full bg-[#ff8a3d]/15 blur-3xl" />
            </>
          ) : null}

          <div className="relative">
            <p className="text-sm font-medium text-white/75">
              {loginContent.eyebrow}
            </p>
            <h1 className="mt-4 max-w-2xl text-4xl font-semibold tracking-tight sm:text-5xl">
              {loginContent.heroTitle}
            </h1>
            <p className="mt-4 max-w-xl text-sm leading-6 text-white/75">
              {loginContent.heroDescription}
            </p>
          </div>

          <div className="relative mt-10 grid gap-3 sm:grid-cols-2">
            {loginContent.featureCards.map((item) => (
              <div
                className={cx(
                  "rounded-lg p-4 text-sm font-medium text-white",
                  isClientAdmin
                    ? "border border-white/20 bg-white/[0.13] shadow-[inset_0_1px_0_rgba(255,255,255,0.18),0_12px_30px_rgba(31,10,49,0.12)] backdrop-blur-md"
                    : "border border-white/15 bg-white/10",
                )}
                key={item}
              >
                {item}
              </div>
            ))}
          </div>
        </Surface>

        <Surface className="p-6 lg:p-8">
          <div className="flex h-full flex-col justify-center">
            <div
              className={cx(
                "inline-flex h-10 w-10 items-center justify-center rounded-md bg-muted text-primary",
                isClientAdmin &&
                  "bg-[#f5effb] text-[#642B93] shadow-[0_10px_30px_rgba(100,43,147,0.10)]",
              )}
            >
              <LockKeyhole className="h-5 w-5" aria-hidden="true" />
            </div>
            <p className="mt-6 text-sm font-medium text-muted-foreground">
              {loginContent.accessLabel}
            </p>
            <h2 className="mt-2 text-2xl font-semibold tracking-tight">
              {loginContent.formTitle}
            </h2>
            <p className="mt-2 text-sm leading-6 text-muted-foreground">
              {loginContent.formDescription}
            </p>

            {errorMessage ? (
              <div className="mt-5 rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-medium text-rose-700">
                {errorMessage}
              </div>
            ) : null}

            <div
              className={cx(
                "mt-5 rounded-lg border border-border bg-muted px-4 py-3 text-sm text-muted-foreground",
                isClientAdmin &&
                  "border-[#e7d9f1] bg-[#fbf7fc] text-[#6d6079]",
              )}
            >
              {loginContent.helperText}
            </div>

            <form className="mt-6 space-y-4">
              <input type="hidden" name="next" value={nextPath} />

              <Field
                id="email"
                label="Email address"
                name="email"
                placeholder={loginContent.emailPlaceholder}
                type="email"
                isClientAdmin={isClientAdmin}
              />

              <Field
                id="password"
                label="Password"
                name="password"
                placeholder="Enter your password"
                type="password"
                isClientAdmin={isClientAdmin}
              />

              <button
                className={cx(
                  buttonBaseClassName,
                  "w-full !text-white",
                  isClientAdmin
                    ? "bg-[#642B93] shadow-[0_14px_30px_rgba(100,43,147,0.22)] hover:bg-[#522178] focus-visible:ring-[#b98bd8]"
                    : "bg-primary hover:bg-primary/90",
                )}
                formAction={login}
              >
                {loginContent.ctaLabel}
              </button>
            </form>

            <Link
              className={cx(
                "mt-6 inline-flex items-center text-sm font-medium text-muted-foreground hover:text-foreground",
                isClientAdmin && "hover:text-[#642B93]",
              )}
              href={loginContent.backHref}
            >
              <ArrowLeft className="mr-2 h-4 w-4" aria-hidden="true" />
              {loginContent.backLabel}
            </Link>
          </div>
        </Surface>
      </div>
    </main>
  );
}

function Field({
  id,
  label,
  name,
  type,
  placeholder,
  isClientAdmin = false,
}: {
  id: string;
  label: string;
  name: string;
  type: string;
  placeholder: string;
  isClientAdmin?: boolean;
}) {
  return (
    <div className="space-y-2">
      <label className="text-sm font-medium text-foreground" htmlFor={id}>
        {label}
      </label>
      <input
        className={cx(
          "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm text-foreground outline-none transition placeholder:text-muted-foreground focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2",
          isClientAdmin &&
            "focus-visible:border-[#642B93] focus-visible:ring-[#c9a7df]",
        )}
        id={id}
        name={name}
        placeholder={placeholder}
        required
        type={type}
      />
    </div>
  );
}
