import Link from "next/link";
import { ArrowLeft, LockKeyhole } from "lucide-react";
import { buttonBaseClassName, Surface } from "@/components/admin/primitives";
import { PLATFORM_NAME, PLATFORM_OWNER } from "@/lib/constants/platform";
import { cx } from "@/lib/utils/cx";
import { login } from "./actions";

type LoginPageProps = {
  searchParams?: Promise<{
    error?: string;
    next?: string;
  }>;
};

export default async function LoginPage({ searchParams }: LoginPageProps) {
  const resolvedSearchParams = searchParams ? await searchParams : undefined;
  const errorMessage = resolvedSearchParams?.error;
  const nextPath = resolvedSearchParams?.next ?? "/admin";

  return (
    <main className="min-h-screen bg-background px-4 py-6 text-foreground lg:px-6">
      <div className="mx-auto grid min-h-[calc(100vh-3rem)] max-w-6xl gap-4 lg:grid-cols-[1fr_440px]">
        <Surface className="flex flex-col justify-between overflow-hidden bg-primary p-8 text-primary-foreground lg:p-10">
          <div>
            <p className="text-sm font-medium text-white/70">{PLATFORM_OWNER}</p>
            <h1 className="mt-4 max-w-2xl text-4xl font-semibold tracking-tight sm:text-5xl">
              NapCart admin for WhatsApp-first restaurant operations.
            </h1>
            <p className="mt-4 max-w-xl text-sm leading-6 text-white/75">
              Configure restaurant identity, branches, operating rules, and
              WhatsApp routing while staff continues receiving orders in WhatsApp.
            </p>
          </div>

          <div className="mt-10 grid gap-3 sm:grid-cols-2">
            {[
              "Owner-facing dashboard",
              "Branch availability controls",
              "Restaurant identity settings",
              "WhatsApp route management",
            ].map((item) => (
              <div
                className="rounded-lg border border-white/15 bg-white/10 p-4 text-sm font-medium text-white"
                key={item}
              >
                {item}
              </div>
            ))}
          </div>
        </Surface>

        <Surface className="p-6 lg:p-8">
          <div className="flex h-full flex-col justify-center">
            <div className="inline-flex h-10 w-10 items-center justify-center rounded-md bg-muted text-primary">
              <LockKeyhole className="h-5 w-5" aria-hidden="true" />
            </div>
            <p className="mt-6 text-sm font-medium text-muted-foreground">
              Admin access
            </p>
            <h2 className="mt-2 text-2xl font-semibold tracking-tight">
              Sign in to the control layer
            </h2>
            <p className="mt-2 text-sm leading-6 text-muted-foreground">
              Use the restaurant admin account created during setup.
            </p>

            {errorMessage ? (
              <div className="mt-5 rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-medium text-rose-700">
                {errorMessage}
              </div>
            ) : null}

            <div className="mt-5 rounded-lg border border-border bg-muted px-4 py-3 text-sm text-muted-foreground">
              Demo credentials are generated by the seed script and stored in
              the local setup notes.
            </div>

            <form className="mt-6 space-y-4">
              <input type="hidden" name="next" value={nextPath} />

              <Field
                id="email"
                label="Email address"
                name="email"
                placeholder="owner@restaurant.com"
                type="email"
              />

              <Field
                id="password"
                label="Password"
                name="password"
                placeholder="Enter your password"
                type="password"
              />

              <button
                className={cx(
                  buttonBaseClassName,
                  "w-full bg-primary !text-white hover:bg-primary/90",
                )}
                formAction={login}
              >
                Sign in
              </button>
            </form>

            <Link
              className="mt-6 inline-flex items-center text-sm font-medium text-muted-foreground hover:text-foreground"
              href="/"
            >
              <ArrowLeft className="mr-2 h-4 w-4" aria-hidden="true" />
              Back to {PLATFORM_NAME} overview
            </Link>
          </div>
        </Surface>
      </div>
    </main>
  );
}

function Field({
  id,
  label,
  name,
  type,
  placeholder,
}: {
  id: string;
  label: string;
  name: string;
  type: string;
  placeholder: string;
}) {
  return (
    <div className="space-y-2">
      <label className="text-sm font-medium text-foreground" htmlFor={id}>
        {label}
      </label>
      <input
        className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm text-foreground outline-none transition placeholder:text-muted-foreground focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
        id={id}
        name={name}
        placeholder={placeholder}
        required
        type={type}
      />
    </div>
  );
}
