import Link from "next/link";
import { PLATFORM_NAME, PLATFORM_OWNER } from "@/lib/constants/platform";
import { login } from "./actions";

type LoginPageProps = {
  searchParams?: Promise<{
    error?: string;
    next?: string;
  }>;
};

export default async function LoginPage({ searchParams }: LoginPageProps) {
  const resolvedSearchParams = searchParams ? await searchParams : undefined;
  const errorMessage = resolvedSearchParams?.error;
  const nextPath = resolvedSearchParams?.next ?? "/admin";

  return (
    <main className="min-h-screen bg-[radial-gradient(circle_at_top,#fff7ef_0%,#f6ebdc_44%,#f2e3d0_100%)] px-6 py-10 text-slate-950">
      <div className="mx-auto grid min-h-[calc(100vh-5rem)] max-w-6xl gap-8 lg:grid-cols-[1.05fr_0.95fr]">
        <section className="rounded-[2rem] border border-black/5 bg-slate-950 p-8 text-white shadow-[0_24px_80px_rgba(110,67,22,0.12)] lg:p-12">
          <p className="text-sm font-semibold tracking-[0.3em] text-amber-200/80 uppercase">
            {PLATFORM_OWNER}
          </p>
          <div className="mt-8 space-y-5">
            <h1 className="max-w-xl text-4xl font-semibold tracking-tight sm:text-5xl">
              Sign in to manage restaurant operations inside {PLATFORM_NAME}.
            </h1>
            <p className="max-w-xl text-base leading-8 text-white/72 sm:text-lg">
              Phase 1 establishes secure admin access for the NapCart
              dashboard. Restaurant data remains scoped to the authenticated
              admin and their assigned restaurant.
            </p>
          </div>

          <div className="mt-10 grid gap-4 sm:grid-cols-2">
            <ValueCard
              label="Phase"
              value="Data + Auth Foundations"
              tone="dark"
            />
            <ValueCard
              label="Auth Method"
              value="Supabase Email/Password"
              tone="dark"
            />
            <ValueCard label="Access Scope" value="Restaurant-scoped" tone="dark" />
            <ValueCard label="Launch Market" value="Pakistan / PKR" tone="dark" />
          </div>
        </section>

        <section className="rounded-[2rem] border border-black/5 bg-white/82 p-8 shadow-[0_24px_80px_rgba(110,67,22,0.08)] backdrop-blur lg:p-10">
          <div className="space-y-3">
            <p className="text-sm font-semibold tracking-[0.25em] text-slate-500 uppercase">
              Admin Access
            </p>
            <h2 className="text-3xl font-semibold tracking-tight">
              Continue to the NapCart dashboard
            </h2>
            <p className="text-base leading-7 text-slate-600">
              Use the restaurant admin account created during seed setup. This
              login is intended for owners and management, while store staff
              continue receiving orders via WhatsApp.
            </p>
          </div>

          {errorMessage ? (
            <div className="mt-6 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-medium text-rose-700">
              {errorMessage}
            </div>
          ) : null}

          <form className="mt-8 space-y-5">
            <input type="hidden" name="next" value={nextPath} />

            <Field
              id="email"
              label="Email address"
              name="email"
              type="email"
              placeholder="owner@restaurant.com"
            />

            <Field
              id="password"
              label="Password"
              name="password"
              type="password"
              placeholder="Enter your password"
            />

            <button
              formAction={login}
              className="inline-flex w-full items-center justify-center rounded-2xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white transition hover:bg-slate-800"
            >
              Sign in
            </button>
          </form>

          <div className="mt-6 rounded-2xl border border-amber-900/10 bg-amber-50 px-4 py-4 text-sm leading-6 text-amber-950/80">
            Demo admin credentials are generated by the seed script. If you
            need them again locally, rerun the seed and use the printed output.
          </div>

          <div className="mt-6 text-sm text-slate-500">
            <Link className="font-medium text-slate-900 hover:underline" href="/">
              Back to project overview
            </Link>
          </div>
        </section>
      </div>
    </main>
  );
}

function Field({
  id,
  label,
  name,
  type,
  placeholder,
}: {
  id: string;
  label: string;
  name: string;
  type: string;
  placeholder: string;
}) {
  return (
    <div className="space-y-2">
      <label className="text-sm font-semibold text-slate-700" htmlFor={id}>
        {label}
      </label>
      <input
        className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-950 outline-none ring-0 transition placeholder:text-slate-400 focus:border-slate-950"
        id={id}
        name={name}
        placeholder={placeholder}
        required
        type={type}
      />
    </div>
  );
}

function ValueCard({
  label,
  value,
  tone,
}: {
  label: string;
  value: string;
  tone: "dark";
}) {
  return (
    <div
      className={
        tone === "dark"
          ? "rounded-[1.4rem] border border-white/10 bg-white/6 p-4"
          : "rounded-[1.4rem] border border-black/5 bg-white p-4"
      }
    >
      <p className="text-sm font-medium text-white/55">{label}</p>
      <p className="mt-2 text-lg font-semibold text-white">{value}</p>
    </div>
  );
}
